pipeline {
    agent {label 'Test'}
    // agent any
    environment {
        // Set your environment variables here


        WAR_FILE = 'target/CalculatorApp-1.0-SNAPSHOT.war' // Adjust this to match your WAR file name

        EC2_IP = '13.211.204.94'
        SSH_USER = 'ubuntu'
        TOMCAT_WEBAPPS_DIR = '/opt/tomcat9/webapps/' // Adjust according to Tomcat installation
        SSH_KEY_PATH = '~/.ssh/id_rsa' // Jenkins server or agent's private key
        
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Pull the code from GitHub repository
                git branch: 'main', url: 'https://github.com/Indrakumar-Mhaski/JavaCalculatorApp.git'
            }
        }
        
        stage('Build') {
            steps {
                // Build the project using Maven
                sh 'mvn clean package'
            }
        }
        
        stage('Deploy to Tomcat') {
            steps {
                // Deploy the WAR file to Tomcat webapps directory
                script {
                    
                    // Copy WAR file to Tomcat webapps
                    sh """
                    scp -i ${SSH_KEY_PATH} -o StrictHostKeyChecking=no ${WAR_FILE} ${SSH_USER}@${EC2_IP}:${TOMCAT_WEBAPPS_DIR}
                    """

                }
            }
        }
    }
    
    post {
        success {
            echo 'Application deployed successfully!'
        }
        failure {
            echo 'Build or deployment failed.'
        }
    }
}
